### ISSUE TITLE
[FE] (QA) Option “not sure” when uncertainties during the QA

### ISSUE THREAD

**Issue by felipelvira** [CCAFS/CGIAR-QA#11]
Thanks to the tag, the uncertain points go into a pool of “ambiguous cases”, that can then be reviewed, either collectively or through a 1:1 during the training sessions.

- [x] Mockup most be provided
- [x] Implementation in QA 2021.

**Deliverable:**
**Move to Review when:** 
**Move to Closed when:**

**Comment by Sagsso** [comment]
Implementation: ![image.png](https://images.zenhubusercontent.com/6006d3a97eacdc817935fd68/c9dbb597-af24-48bb-b594-7825aaec23a9)
