### ISSUE TITLE
Mark/Tag Publications reviewed by WoS

### ISSUE THREAD

**Issue by htobon** [CCAFS/CGIAR-QA#16]
This new reporting round, we will receive a list of peer-reviewed papers from CRPs in which we expect most of them will be checked using Web of Science (WoS). Which means that the metadata information coming from it (e.g. title, description, authors, open access, ISI, etc.) is the one that will be treated as official and will not be validated by any of the assessors.

As a result, please make sure that all peer-reviewed papers validated by WoS are properly tagged in the system so that Assessors do not need to check them all but only focus on the ones that were not.

It would be great to start this development with a couple of mockups on how the interfaces will look like and validate them with Lea and me directly.

**Comment by Sagsso** [comment]
Automatically validated tag: ![image.png](https://images.zenhubusercontent.com/6006d3a97eacdc817935fd68/0b34d249-12d4-4bc7-9ac7-94e5dd421dba)

Peer-Reviewed Papers status chart: ![image.png](https://images.zenhubusercontent.com/6006d3a97eacdc817935fd68/4c54ca36-449e-4891-adcd-5a5b270824dd)
