### ISSUE TITLE
[FE] (QA) “Already seen” button (to check if the second assessor has seen the comment from assessor 1)

### ISSUE THREAD

**Issue by felipelvira** [CCAFS/CGIAR-QA#7]
To identify if assessor 2 has seen comments made previously by assessor 1.

- [ ] Mockup most be provided (prepare for approval). 
- [ ] Implementation in QA 2021.

**Deliverable:**
**Move to Review when:** 
**Move to Closed when:**

**Comment by Sagsso** [comment]
The feature was developed but will not be considered now.
